
[column_names_map]
d15N_N2Oa_mean = "d15N-N2Oa_mean (per mil vs. atm N2)"
d15N_N2Ob_mean = "d15N-N2Ob_mean (per mil vs. atm. N2)"
d18O_N2O_mean = "d18O-N2O_mean (per mil vs. VSMOW)" 
N2O_mean = "N2O_mean (nM)"     
d18O_NO3_mean = "d18O-NO3 avg (per mil vs. VSMOW)" 
d15N_NO3_mean = "d15N-NO3 avg (per mil vs. atm. N2)" 
d15N_NO2 = "d15N-NO2 (per mil vs. atm N2)"    
d18O_NO2 = "d18O-NO2 (per mil vs. VSMOW)" 
Nitrite = "Nitrite [uM]"               
Oxygen = "Seabird Oxygen [umol/L]" 
NO3_mean = "NO3_mean (uM)"                      
Depth = "Target Depth [m]"

[derived_columns]
inv_N2O_mean = "1/N2O_mean"

[clustering_settings]
class = "aicv.cluster.leiden.LeidenCluster"
cols_to_cluster = [
    "d15N_N2Oa_mean", "d15N_N2Ob_mean", "d18O_N2O_mean", 
    "N2O_mean", "d18O_NO3_mean", "d15N_NO3_mean","d15N_NO2", "d18O_NO2", "Nitrite",                                  "Oxygen", "NO3_mean", "Depth"]
perplexity = 20
new_col_name="cluster"
add_tsne_embedding = true
